---

# Initialize the Language
language: python

# Declare Docker Service to be used in the build
services: docker

# Environments variables for test
env:

    # Global
    global:
        - ROLE_NAME: initserver
        - AUTHOR: jetune
    matrix:
        - MOLECULE_DISTRO: v1.1.0-centos7-py3
        - MOLECULE_DISTRO: v1.1.0-xenial-py3
        - MOLECULE_DISTRO: v1.1.0-bionic-py3

# Before install actions
before_install:
    - docker pull kubecloudsas/docker-ansible-test:v1.1.0-centos7-py3
    - docker pull kubecloudsas/docker-ansible-test:v1.1.0-xenial-py3
    - docker pull kubecloudsas/docker-ansible-test:v1.1.0-bionic-py3

# Installation actions
install:

    # Install Test tools
    - pip3 install molecule docker molecule-docker flake8

    # Uninstall testinfra 1.19.0
    - pip3 uninstall -y testinfra==1.19.0

    # Install testinfra 3.0.5
    - pip3 install testinfra==3.0.5

# Test scripts
script:

    # Run Tests
    - molecule test --all

# Norifications
notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
